### ISSUE TITLE
Quellentyp ergänzen (593)

### ISSUE THREAD

**Issue by MFalletta** [rism-international/iccu#1]
In vielen Titeln stehen in 260 $a Angaben für den Quellentyp:
Autografo incerto → 593 Possible autograph manuscript
Beispiel: 850687470

Autografo → 593 Autograph manuscript
Beispiel: 850817409

Copia ms → 593 Manuscript copy
Beispiel: 850794197

Copia → 593 Manuscript copy
Beispiel: 850817699

Begriffe in 260 $a können nach Umsetzung gelöscht werden.

**Comment by HirschSt** [comment]
same as https://github.com/rism-international/tasks/issues/535
