### ISSUE TITLE
Katalogisierungsprache 040 $b

### ISSUE THREAD

**Issue by MFalletta** [rism-international/iccu#2]
Italienisch

**Comment by HirschSt** [comment]
@MFalletta danke; bitte issues, die sich nicht explizit an die BSB richten (https://github.com/rism-international/opac-report) oder zur Muscat-Entwicklung beitragen (https://github.com/rism-ch/muscat) unter https://github.com/rism-international/tasks/issues eintragen

same as https://github.com/rism-international/tasks/issues/473
